#ENC[AES256_GCM,data:3s1lfU0Q7h5DIynVqNJPVdYdTdakRti0fg==,iv:1S0z8+tovzJsnpchQpiyOrAaxxOibaQcYBfZIJZonXg=,tag:3aCJiNbFS87RhT/yb7FhRg==,type:comment]
#ENC[AES256_GCM,data:0BunKanXCLnyjyuNPrMjogLrZDTCggUnwKQV8gxJw8cw7WORkYOpjJk+nZrixxvi8GjmA8gdHxmqlgUXzRJ5pkQu4HxMTDzLTvND+HHt,iv:IzDKQcv6BTnX/OZsNfxOnXi/1LHKkKOkZIenmdbvrug=,tag:dK8ZG5UjiLNPtErrozIVVw==,type:comment]
#ENC[AES256_GCM,data:ur0eU6PAF7tSdWKTZ/r4cFwrXoxpLvooW2JK0/CigDA2Zy9IuI/QBUu92bORS1xaqYS2s3GShf9RD9lZt4R2Qa3IZwW9kVLITva9kRScfYoA,iv:6skeJiGX/usMk6BlYWXHXJeA285v5ii3bjD8xGoG7k0=,tag:JRjDL63mnORh87MCb6VY8A==,type:comment]
spring:
    profiles:
        active: ENC[AES256_GCM,data:qxR7ig==,iv:mD5JJcKy+fkDLwlXII1MBSTax9vL5ZRYwNpVdohTB6M=,tag:6qqzf36OR5uugIPn6+0VDg==,type:str]
    mongodb:
        uri: ""
    mail:
        host: ""
        port: ENC[AES256_GCM,data:/v4H,iv:TfcSoHZwlk2T2v2dWA9l/jCOloQH4L2jZfHnhzcT3Mc=,tag:+GskbV6eeYvQuxbtVrPhUg==,type:int]
        username: ""
        password: ""
        properties:
            mail:
                smtp:
                    auth: ENC[AES256_GCM,data:w+Twdw==,iv:M2g4ykRR6q9Teb3RIead9iJJcQKhJNDs3ld/uBgtUic=,tag:StutZlpdggFDIqlV0+TpBQ==,type:bool]
                    starttls:
                        enable: ENC[AES256_GCM,data:I3IO5w==,iv:I3K+3yeVnk7w1hd5lTrH4s0HGtbFwksuK63M0Sg2KyA=,tag:ym7ROxkFaHXRSuV1FPWreA==,type:bool]
openai:
    api-key: ""
    api-url: ENC[AES256_GCM,data:HSt3rxf6QHavJ5LEplys07WdBpisr5e0dfmdnDefhMnQdzjUc0T22vxa,iv:67lcBPfakUNOwrrL98jb2mQMlZ1Hdbpew6y1dKe0drU=,tag:4UQ4MIIOTj650102y51e2A==,type:str]
jasypt:
    encryptor:
        password: ""
news:
    api:
        key: ""
app:
    admin:
        allowed-usernames: ""
        bootstrap-username: ""
        bootstrap-password: ""
        bootstrap-email: ""
    notification:
        email:
            recipient: ""
            from: ""
    news:
        naver:
            client-id: ""
            client-secret: ""
        gnews:
            api-key: ""
    market:
        fx:
            api-key: ""
        gold:
            api-key: ""
        oil:
            api-key: ""
        dxy:
            api-key: ""
        index:
            api-key: ""
sops:
    age:
        - recipient: age1vmhxgfsctfr2pvyy9u76slah30wyje26p2tew6zcgx5lp9fhp9fq0ghmrl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNRTVxUnBqUUgwU01pNmsw
            VExmdzM0a3lMTGRTTWNpYk8zY0dEQTc3L1ZVCjE0S21uRVI5VHNKVkN2ODZJL0xB
            a1cvNHNEaUd5M0F1MWF3QW9MZlFxK2cKLS0tIHJVYU85Skp0YmdUV0N0Y0ZiOUlx
            OTdsVElISzRqNkVXMHVSNXY1cyszcUUK09I8aPXh/bWwZH4DX5Q5BASNhHcli18o
            Wqpf4PaKJNzXcaoCeCbR6HO6H9i/1BBBmfFiUKfmTKB56mOM4wdyIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T01:21:51Z"
    mac: ENC[AES256_GCM,data:IK9EZQWkOqPUwznN4DAQ22KVGlVuHWj74Maa0Td74kN0S3mHQuW3ShgAF2Y6ceKrjO3ZNMb/Apojo7bvCTn4V6UOY68BHvK76LHid8yNSmthFhtawdw8fJ/HJ0DU1VG+G+Brhgxya5VeTRENwMNI1jtzFHR9AV29Sj6mLPWOdVI=,iv:t0HXP/DS6M0PPIpe2PSG8qATe17KyxhE1KR5Z0j8fjY=,tag:q5zS8eL3rI3/p4gTSnKFMQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
