#ENC[AES256_GCM,data:CR8wpuA3893Z6O8+RkaGhH/Db/1V3fU/JQ==,iv:iZsmLyEc9XdHf1tYj6g8ZrMaRZkgZ+dTcLSJ9n5FeEA=,tag:QvtHsBiGNFRBlFg3WfJdNA==,type:comment]
#ENC[AES256_GCM,data:8VRSRW/OB7B+qPlIRuZ7c3X9IfKJIuB5xSyl3CUvI1pmBXNBoDA762l+bkCSPW+slGMmFNlhMlVr/iSf0k3k9gigMkDIuNQI2Hw5KpDh,iv:evWYQr8A0R+WBRP3ZJQMG2xMnj6B3R4nLKqEYrjzQZs=,tag:mOpRU4+ztGoNU0wqDJmb1A==,type:comment]
#ENC[AES256_GCM,data:C844nX0elWSxe8KgjEVfrKAJHHh+IXK9fq+KEzZTIDWpjZjqhHtqjPUEQ0QqZXpTp+j6r5Ypt276oPMeacWOGSN59awcQdcq42K0Du0VQrZ2,iv:3//aBBd1nOxD9+A48Ef2yh13dXCUWf2kYQAo3EPvvek=,tag:sqTsnbIy0FMIWzgXY2DwGA==,type:comment]
spring:
    mongodb:
        uri: ENC[AES256_GCM,data:Zcn5d5mM5sCvt4xYsoHx2YAX8owzE3ZzSTFqn2dRztAsVfI6RSimNXOy4gzRvNA9jcMUlcihJlkVv38RapQc6l+JsH/z6w0Zwit+5hoO0KfEu/HY0Oyj+2VAbll6Tb4/Kmmg,iv:TLEDVcRI6vpm5A7CMTIaXCf1CbWpT+obMYKt2dK58z4=,tag:s6K0bsCGmK8QEbnQPaxHWw==,type:str]
    mail:
        host: ""
        username: ""
        password: ""
openai:
    api-key: ENC[AES256_GCM,data:88/G2JFvM3Gb8NQPIkYbvjVtfPbBc6WNWuYBk2ps7UNhBtyOSpGJRuslVY8ANomyHKX8g6G4aQwFT+rQAKWGoybY+esDztIJ5EuvphCpgBiaY/pK9wFo2fbclWoObPYAOOvCWs/3h+TM7pKUSYVgAKJR8blsnbdu0dAmzxddC7zRU6uawBNTN7YdpotnhlJNkMNJ8XYNZYAsJtpY5BDtPcD/CFg=,iv:JXxt/ZbdCZfv+Ig59sZxTeBzER+G+8rkaa42x33z4Dg=,tag:K1k3POzwhp0Dc5Cl8P1Afg==,type:str]
jasypt:
    encryptor:
        password: ""
news:
    api:
        key: ENC[AES256_GCM,data:fBFrDknFlJBN+6aQhpg1iFCgLLuyxkP3oyS4QpUeay0=,iv:4CizjoK0nhY2z8Vy1YYxf6WIWkYkdS2tw2YLyHMYQfY=,tag:JQKT8TtniINSRmKA6k4QzQ==,type:str]
app:
    admin:
        allowed-usernames: ENC[AES256_GCM,data:UO4NLeUV1w==,iv:pB1bpXH4/eoA1ggGUo/E11+VoD4JSb22ZuT2uuPQ/t0=,tag:PVEBE7/FVJNP56Omvs6Uxg==,type:str]
        bootstrap-username: ENC[AES256_GCM,data:kwvNGrldLw==,iv:He5VBlcQZQmTRjCGsFdDN58fco2Z0Sk4+I/z1mXC9ug=,tag:/AFKV+S0XptdZWGLWzwJaQ==,type:str]
        bootstrap-password: ENC[AES256_GCM,data:h4VGW3Xx4BHiLmD+,iv:J8DDqRNcgjD/A8hCQzw7q2kO2lsbEziUma2Mp+SXvTU=,tag:rsR+gLq+b8gDFlK3d+H3Hw==,type:str]
        bootstrap-email: ENC[AES256_GCM,data:TbecBxZJ4bpDa3MZWsFbgQA=,iv:ZcdgARI6boNb+rpsj2bBiX30PGnT+o6wr5AMYSbiwr4=,tag:rwFYbWnsqspw4azvLWV74g==,type:str]
    notification:
        email:
            recipient: ENC[AES256_GCM,data:p5VRE04iNf42tqSsD4G0JZw=,iv:QxwRywpDNwWAmHshz7YG1Pm7v4k+gryAStCLFZeyTOg=,tag:RAADGGbsJk8GvwWxN26o1g==,type:str]
            from: ENC[AES256_GCM,data:LWAugfW1FNpn/wIq1wxEDPc=,iv:ayrkoL3/MXVdS6Y/y+10f1S1AdsbVo10XyQQt3pB7fA=,tag:ixeg/3ubPeFJNUW2FDYNyQ==,type:str]
    news:
        naver:
            client-id: ENC[AES256_GCM,data:v945Dgafz7bWHMFQt5EVxj1YUjs=,iv:09Wd7GQloCKHMFuo1yVfXSOFR4KGjQwLI6CUVZNbIpg=,tag:OWI/Jiy8Hlign5U1Hza4cg==,type:str]
            client-secret: ENC[AES256_GCM,data:0eFXBjOx0bDPcQ==,iv:DvUuVQBvd1ysqaNiEyHj95G861mho4ZAtWrJ2/8xufM=,tag:yfHrz4vzLUkT/XvbHFx4bw==,type:str]
        gnews:
            api-key: ENC[AES256_GCM,data:T7OaY69iHFZIM+2BoShapOoAHo2I31LdEuNYM6NHvgQ=,iv:aR9FpWQEnsaG8nidnXPZ3OWmUHhhF6TUDD8bOzN9s8Y=,tag:Jhg/9PCz+aehoxfQ+lHndw==,type:str]
    market:
        fx:
            api-key: ""
        gold:
            api-key: ""
        oil:
            api-key: ""
        dxy:
            api-key: ""
        index:
            api-key: ENC[AES256_GCM,data:htspduLVXIjQMj86lCtfmWU9iasre7KTpW99EqzNBpbMihvLMZs/SQkk6S+B9amrJOUEGJQxzJc7YYjSqDXiUQ==,iv:QG4H/6CH+wu4PoPvLnwEGwHSlburDYaziP/z1eGMdbw=,tag:V5bEUVq5YDKdL9/KSSx+lg==,type:str]
        us10y:
            api-key: ""
sops:
    age:
        - recipient: age1vmhxgfsctfr2pvyy9u76slah30wyje26p2tew6zcgx5lp9fhp9fq0ghmrl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxVzVhT0Q2cWJBb0pGTENq
            WkViV252YU9xbWRKUkFCbXhWSUFIazJNOVF3ClVkbHlaYjR6SWpuMUFRZE41b3BD
            YUhUWFN1Vk5jRWNkRWcrUmZpNWRPMUEKLS0tIDh6SkdkaE1uNXVSRndYVnNxbEcv
            N09LMGtGdlVDT2FPd292QU83WkxCQjAKs40HozqECEQmhzNAjmncigkFSRJkw4yn
            Wq/7WaFG8VQsHUdyd3Gr0VLLuYL7rhDLGxNjnIMX4YzQu14F2Qk8DQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-11T03:23:24Z"
    mac: ENC[AES256_GCM,data:dGpWPG/vM90DLJf1cw4yaZgrNWQf95dMenAemKOuMf0ko0Aprx22ZiDk6pRjYPIwWBXxJIeKT4QyvrtvwG4MdXWC57MA3v6ayx5x7MrcKNvJqydik1pc7tr8SPW2mtKaJe0JqfcYXoH0uMyOykrcCl0gra9Q8I/dXX+mv91HtVA=,iv:Ga3kMFSZPKyLD/vxiVhK91OxPYLKcaDViXqLl+5KDB0=,tag:BVkV9K21CrzzkLGqn6esNQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
