server:
  port: 8082

spring:
  application:
    name: macro_news

  data:
    mongodb:
      uri: mongodb://localhost:27017/macro_news

  mongodb:
    transactions:
      enabled: true # Replica set required in production for this to take effect

  thymeleaf:
    cache: false

  web:
    resources:
      cache:
        period: 0

  devtools:
    restart:
      additional-paths: src/main/resources
      enabled: true
    livereload:
      enabled: true

  security:
    user:
      name: user
      password: pass123

  mvc:
    problemdetails:
      enabled: true

openai:
  api-key: ENC(37uGeEjg5tDfzeGJAUCAspd5tnn1K9Zi9dj7oxRJMj1aJ1820o3oI35dg1NDkHS7DJBhD0KgVk0GSaHatCXYlDbZOJBbzTke76dEwREtY5Iu8xPly4/1WGw63KOP0vgDvD4fFKII2sLJd8xh6XqPu6T+deFREfm0TMXZ5il0VDgseR4mSJCQan1y+VeHBJsGR9HtxP2NuNoygXDFyE3w2j56tHR+PES9IsgWDhjnupIoore6XAFjQPiRH5NdGx44h/BfOstt8cmQ+uFKX/kwOw==)
  api-url: https://api.openai.com/v1/chat/completions
  models-url: https://api.openai.com/v1/models
  model: gpt-4o-mini
  max-tokens: 800
  temperature: 0.7
  macro-prompt-file: classpath:ai/prompts/macro_interpretation_prompt.json

jasypt:
  encryptor:
    password: open_ai_secret

news-api:
  provider: RSS
  rss-url: https://news.google.com/rss/headlines/section/topic/BUSINESS?hl=en-US&gl=US&ceid=US:en
  default-page-size: 10

logging:
  config: classpath:log4j2-spring.xml
